name: NodeJS Dependencies
"on":
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - pnpm-lock.yaml
      - "**/package.json"
env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  sherif:
    runs-on: lynx-ubuntu-24.04-medium
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"
      - run: |
          pnpm dedupe --check
          pnpm dlx sherif@latest
